### ISSUE TITLE
[Suggestion] Show durability via overlay GUI or a Waila tooltip

### ISSUE THREAD

**Issue by Yuudaari** [codetaylor/advancedmortars#17]
You can't currently see the durability of a mortar without picking it up (as far as I can tell). It would be nice to be able to tell how much longer a mortar will last without picking it up.

**Comment by codetaylor** [comment]
What if the durability was displayed in the overlay and, if Waila is present, it's displayed there instead?

**Comment by Yuudaari** [comment]
Sounds good to me!

**Comment by codetaylor** [comment]
Do you have any suggestions for the presentation of the durability in the overlay?

I was thinking of just having a small bar that depleted with use. It would have a single pixel outline to highlight the negative space (missing durability) and make it easier to read. My concern with this approach is that the user may read the bar as a crafting progress bar and think that the mortar is not working. Hopefully it would become evident what the bar is once it changes. It would not change very quickly with a high durability mortar.

I want to refrain from adding more icons to the overlay. I believe that icons are not inherently readable and only become readable after an understanding of the icon's intent is reached. A wall of foreign symbols can be daunting.

I'm a big fan of Botania's design ethos, found [here](https://botaniamod.net/). Specifically the bit about in-world interactions and not displaying numbers to players.
