### ISSUE TITLE
Log Output JEI Support

### ISSUE THREAD

**Issue by Xaikii** [codetaylor/advancedmortars#29]
Crash report:
https://gist.github.com/codetaylor/b96c10547fd5ffb0413d6a3ba7c8b928

**Comment by codetaylor** [comment]
Thanks for the report, I'll look into this. In the future, please use gist, pastebin, hastebin or something similar to post crash reports.

**Comment by codetaylor** [comment]
Can you please post the script that causes the issue?

**Comment by codetaylor** [comment]
What version of JEI?

**Comment by codetaylor** [comment]
The default recipes are added internally and used explicit null values for the secondary outputs. This caused the errors with JEI when it attempted to retrieve a `.copy()` of null.

Fixed in 1.12.2-1.6.20

**Comment by Xaikii** [comment]
Oh yeah I didn't get notified that you wrote, I forgot to use pastebin, I think I didn't because it was that short, and yeah no recipes are actually made in the Profile where the logs are out.

Also in the new version this seems to be fixed with latest version
