### ISSUE TITLE
Support CraftTweaker's IngredientOr

### ISSUE THREAD

**Issue by Yuudaari** [codetaylor/advancedmortars#30]
[CraftTweaker supports an "or" construct for providing multiple valid items without using the ore dictionary.](http://crafttweaker.readthedocs.io/en/latest/#Vanilla/Variable_Types/IIngredient#or-ing-an-iingredient)

Using this in an Advanced Mortars recipe errors with `[AVAILABLE][CLIENT][ERROR] Unknown input type: crafttweaker.api.item.IngredientOr@31fb8f4d`.

**Comment by guillaumearm** [comment]
👍 This would be very appreciated
