### ISSUE TITLE
Mortar item textures

### ISSUE THREAD

**Issue by duely** [codetaylor/advancedmortars#38]
I think this could be classified as a "feature request". I don't understand the code well enough, but I've noticed that a number of mods use object models as their icon (specifically HorsePower), and it would certainly be great if, especially for higher resolution texture packs, the models themselves were used instead of the current icon.

Feel free to disregard! I gave it an attempt myself but, as a beginner with all things mods, gave up until I can fully understand the system.

**Comment by codetaylor** [comment]
Feature available in 1.12.2-1.7.0

**Comment by duely** [comment]
I have to laugh at how little I knew back then! Ahahaha.
