### ISSUE TITLE
Does using a Mortar cost Hunger?

### ISSUE THREAD

**Issue by nmarshall23** [codetaylor/advancedmortars#4]
If it doesn't I would like the option to set a global amount for Hunger cost per click.

This would let me replace the Manual Millstone in Better with Mods with a Mortar crushing Crushing Recipe.

**Comment by codetaylor** [comment]
It currently doesn't cost any hunger.

**Comment by codetaylor** [comment]
Implemented in 1.12.2-1.1.4

**Comment by nmarshall23** [comment]
Wow, you are fast. 
I do have a small issue with your implementation, maybe try adding Exhaustion to the player. 
This would use the player's saturation first then hunger. This would also prevent their hunger from going negative. 

Here is an example from [BetterWithMods](https://github.com/BetterWithMods/BetterWithMods/blob/0bd46da7b83e9c1dd5c85179fb5bea1da3d07b1b/src/main/java/betterwithmods/common/blocks/mechanical/BlockCrank.java#L81)

```
if (player.getFoodStats().getFoodLevel() > minHunger) {
  player.addExhaustion((float) ModuleConfig.RECIPES.HUNGER_COST_PER_CLICK);                  
}
```

**Comment by codetaylor** [comment]
Yeah, I was wondering about saturation, but wasn't sure how to implement it. Thank you for the example! :) I will look into this tomorrow.

**Comment by codetaylor** [comment]
Ok, I've re-implemented this feature with different mechanics.

This is what the config looks like with default values:

```
# Amount of exhaustion to charge the player per click required to complete a recipe.
# Set to 0 to disable.
# Min: 0.0
# Max: 40.0
D:EXHAUSTION_COST_PER_CLICK=0.0

# Minimum amount of hunger the player needs to operate a mortar.
# Set to 0 to disable.
# Min: 0
# Max: 20
I:MINIMUM_HUNGER_TO_USE=0
```

... and the implementation:

```java
if (player.getFoodStats().getFoodLevel() > ModuleConfig.RECIPES.MINIMUM_HUNGER_TO_USE) {
  // Only perform crafting if the player has enough hunger

  if (tile.incrementCraftingProgress()) {
    // Only inflict exhaustion if the crafting process was incremented
    player.addExhaustion((float) ModuleConfig.RECIPES.EXHAUSTION_COST_PER_CLICK);
  }
}
```

This implementation seems to provide the requested functionality. It does not actually directly cost the player hunger, instead it reduces saturation. If the player's hunger level is above the configured amount, they can use the mortar.

I did not implement a message to the player that they are required to eat if they don't have a sufficient hunger level. If you would also like the player to be notified, I would like to think of a different way of notifying the player. I'm not too keen on mods that print messages to the chat.

Let me know if this meets your needs.

**Comment by codetaylor** [comment]
I'm going to go ahead and close this in order to get the next release out. The next release contains a significant change in functionality and I want to get it out as soon as possible.

Regardless, please give me your feedback.
