### ISSUE TITLE
Jei weird interaction

### ISSUE THREAD

**Issue by Mrthomas20121** [codetaylor/advancedmortars#40]
if you have 2 items on a mortar recipe. it doesn't show the item name if you are on the left of the item. but on the right(still with the cursor on the item) it show the name.
![image](https://user-images.githubusercontent.com/34064092/57623040-3155f200-758f-11e9-93f5-664121303222.png)

**Comment by codetaylor** [comment]
Fixed in 1.12.2-1.6.23

![image](https://user-images.githubusercontent.com/1240716/57738636-25d4fa80-7665-11e9-8120-9d1899437e15.png)
