### ISSUE TITLE
Game unexpectedly crashes when trying to mix

### ISSUE THREAD

**Issue by Thaumatarge** [codetaylor/advancedmortars#7]
Whenever I try to use a mixing recipe my game unexpectedly crashes and I have no clue why; the crash report says that there is a class missing.
Here is the crash report:
[crash-2017-12-19_22.33.16-client.txt](https://github.com/codetaylor/advancedmortars/files/1573350/crash-2017-12-19_22.33.16-client.txt)

**Comment by codetaylor** [comment]
This project was built against Forge version: 14.23.1.2556
I notice you are using version: 14.23.0.2529

Try updating Forge to at least 14.23.1.2556 and see if the problem persists.

**Comment by codetaylor** [comment]
It looks like the class in question (net/minecraftforge/common/util/RecipeMatcher) was created only 27 days ago in this commit: https://github.com/MinecraftForge/MinecraftForge/commit/89db87dbfce4e4bd130f5daccac7cac495002275#diff-47a542098b32286697faf16095ae8c7c

That class probably isn't available in your version of Forge, hence the missing class.

**Comment by Thaumatarge** [comment]
Oh, I haven't updated my forge in a while, but it did fix the issue.

Thanks!

**Comment by nmarshall23** [comment]
I'm getting a crash with latest release. [Crafttweaker.log](https://pastebin.com/0f1Dja4C)
Advanced Mortars version 1.2.6
Craft Tweaker 2 version 4.0.10
Forge-14.23.1.2578

My Crafttweaker script:
```
import mods.advancedmortars.Mortar;

Mortar.addRecipe(["iron", "stone"], <minecraft:flint>, 25, [<minecraft:gravel>]);
```

**Comment by codetaylor** [comment]
This is unrelated to this issue. I've moved it here: https://github.com/codetaylor/advancedmortars/issues/10
