### ISSUE TITLE
Mortar Recipes - Optional give back item

### ISSUE THREAD

**Issue by nmarshall23** [codetaylor/advancedmortars#9]
I was thinking about adding a Recipe for Tinkers Construct Grout, that would take a water bottle and give back an empty bottle. 

What do you think? Is that functionally a good feature?

**Comment by codetaylor** [comment]
What about an optional second recipe output with a percent chance? This would add an existing ZenScript method like so:

```
Mortar.addRecipe(String[] mortarTypes, IItemStack output, int duration, IItemStack secondaryOutput, float secondaryOutputChance, IIngredient input);
```

In your case, the empty water bottle could be configured as the secondary output with a 1.0 chance.

**Comment by nmarshall23** [comment]
Yes, that's what I was thinking of.

**Comment by codetaylor** [comment]
Completed in e8556898b6ec3626fd16b37d632e7238389e1943.

Feature will be available in the next uploaded build.
